// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0MlLo3yqqMs9Uo0zVDQ5Bul4kvOtwia8',
    appId: '1:1068839567989:web:3c6b35e8326a43e2f66e3c',
    messagingSenderId: '1068839567989',
    projectId: 'tourister-3541c',
    authDomain: 'tourister-3541c.firebaseapp.com',
    storageBucket: 'tourister-3541c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF9BNi0tOyGauSDlb1LG6wV63p5dfARf0',
    appId: '1:1068839567989:android:271d8e13f9447574f66e3c',
    messagingSenderId: '1068839567989',
    projectId: 'tourister-3541c',
    storageBucket: 'tourister-3541c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCygQswrPi80NCZbdky7dxq7oZQWRo5YR0',
    appId: '1:1068839567989:ios:00dd9e2c6c41b599f66e3c',
    messagingSenderId: '1068839567989',
    projectId: 'tourister-3541c',
    storageBucket: 'tourister-3541c.appspot.com',
    iosClientId: '1068839567989-v39ju7gs0p1pkdi8m1f5k7kuhhbds3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCygQswrPi80NCZbdky7dxq7oZQWRo5YR0',
    appId: '1:1068839567989:ios:b05bc9772daa718af66e3c',
    messagingSenderId: '1068839567989',
    projectId: 'tourister-3541c',
    storageBucket: 'tourister-3541c.appspot.com',
    iosClientId: '1068839567989-ft5vp5bhajlpk09dgaeapf56m85f5fli.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourister.RunnerTests',
  );
}
